data:
  # can be used in iptable templates
  external: enp4s0f1
  internal: &interface enp8s0

iptables:
  - POSTROUTING -t nat -o {external} -j MASQUERADE

node_iptables:
  # the bridge can connect to the internet
  - FORWARD -i {bridge} -o {external} -j ACCEPT
  - FORWARD -o {bridge} -i {external} -m state --state RELATED,ESTABLISHED -j ACCEPT
  # the management network can connect to the bridge
  - FORWARD -i {internal} -o {bridge} -j ACCEPT
  - FORWARD -o {internal} -i {bridge} -m state --state RELATED,ESTABLISHED -j ACCEPT

nodes:

  ping:
    interface: *interface
    vlan: 3
    address: 172.16.0.104/24

  pong:
    interface: *interface
    vlan: 4
    address: 172.16.1.105/24